### PR TITLE
PRIME-1615 Multiple tech support contact(s) and PharmaNet admininstrator(s)

### PR DESCRIPTION
**Pull request by mtpultz**

### CODE REVIEW

**Comment by johnnyl6** [comment]
When doing a regular site registration and visiting Pharmanet administrator page, got an error. It seems that the excludeList input of ContactProfileFormComponent needs to be initialized. 
```
Cannot read property 'includes' of undefined Object
print @ logger.service.ts:69
logger.service.ts:69 Cannot read property 'includes' of undefined Object
print @ logger.service.ts:69
zone-evergreen.js:171 Uncaught TypeError: Cannot read property 'includes' of undefined
    at ContactProfileFormComponent_Template (contact-profile-form.component.html:39)
    at executeTemplate (core.js:7457)
    at refreshView (core.js:7326)
    at refreshComponent (core.js:8473)
    at refreshChildComponents (core.js:7132)
    at refreshView (core.js:7376)
    at refreshComponent (core.js:8473)
    at refreshChildComponents (core.js:7132)
    at refreshView (core.js:7376)
    at refreshEmbeddedViews (core.js:8427)
```

**Comment by johnnyl6** [comment]
Goe frontend error at the administrator page during regular site registration

```
Uncaught TypeError: Cannot read property 'includes' of undefined
    at ContactProfileFormComponent.toggleAddressValidators (contact-profile-form.component.ts:176)
    at ContactProfileFormComponent.ngOnInit (contact-profile-form.component.ts:111)
    at callHook (core.js:3281)
    at callHooks (core.js:3251)
    at executeInitAndCheckHooks (core.js:3203)
    at selectIndexInternal (core.js:6270)
    at Module.ɵɵadvance (core.js:6252)
    at AdministratorPageComponent_Template (administrator-page.component.html:22)
    at executeTemplate (core.js:7457)
    at refreshView (core.js:7326)
toggleAddressValidators @ contact-profile-form.component.ts:176
ngOnInit @ contact-profile-form.component.ts:111
callHook @ core.js:3281
callHooks @ core.js:3251
```

**Comment by mtpultz** [comment]
> Goe frontend error at the administrator page during regular site registration
> 
> ```
> Uncaught TypeError: Cannot read property 'includes' of undefined
>     at ContactProfileFormComponent.toggleAddressValidators (contact-profile-form.component.ts:176)
>     at ContactProfileFormComponent.ngOnInit (contact-profile-form.component.ts:111)
>     at callHook (core.js:3281)
>     at callHooks (core.js:3251)
>     at executeInitAndCheckHooks (core.js:3203)
>     at selectIndexInternal (core.js:6270)
>     at Module.ɵɵadvance (core.js:6252)
>     at AdministratorPageComponent_Template (administrator-page.component.html:22)
>     at executeTemplate (core.js:7457)
>     at refreshView (core.js:7326)
> toggleAddressValidators @ contact-profile-form.component.ts:176
> ngOnInit @ contact-profile-form.component.ts:111
> callHook @ core.js:3281
> callHooks @ core.js:3251
> ```

Thanks @johnnyl6 :) I might have fixed this already when fixing a similar issue in the admin, but will have a look right now to make sure.  We should make it a habit to use review comments so we can mark them as resolved, and can reply directly to the comment.

**Review by johnnyl6 — APPROVED** [review]
LGTM Alt text

**Review by AnaisHebert — APPROVED** [review]
✔✔🦆

**Review by johnnyl6 — APPROVED** [review]

**Pull request merged**
