### PR TITLE
Remove State Machine from SubmissionStateEngine

### PR DESCRIPTION
**Pull request by james-hollinger**
C# 8's new switch expression makes our state machine syntax kinda unnecessary. So I removed it.

### CODE REVIEW

**Comment by neophyte57** [comment]
I think it would be useful to add a comment that references the documentation for the newish syntax (e.g. https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#switch-expressions) even if the feature was available in September 2019

**Review by AnaisHebert — APPROVED** [review]
Wooo its beautiful🍰

**Review by johnnyl6 — APPROVED** [review]
👍

**Review by mtpultz — APPROVED** [review]
🐕‍🦺

**Pull request merged**
