### PR TITLE
[ops] add helm charts / deployment

### PR DESCRIPTION
**Pull request by i5okie**
- Replacing OpenShift resource templates with Helm charts
- Update Github Workflows to deploy with Helm charts

### CODE REVIEW

**Comment by neophyte57** [comment]
Getting this, problem with Doc Manager?

image

**Comment by AMiKaH** [comment]
Same issue that Alan is having with doc manager
image

**Comment by Paahn** [comment]
Getting the docman error on PR environment, but docman works fine on local branch.

**Comment by AMiKaH** [comment]
Looks good!

**Review by AMiKaH — APPROVED** [review]
Looks good!

**Review by Paahn — APPROVED** [review]
🚀

**Pull request closed without merging**
