### PR TITLE
PRIME-2332 Vendor selection limited by care type (Health Authority Site Registration)

### PR DESCRIPTION
**Pull request by neophyte57**
- `HealthAuthorityService.GetVendorsByCareTypeAsync` not needed at this time but did not remove 
- Several Health Authority pages on admin side are broken by this model change so relying on data load from Excel spreadsheet to populate database, for time being
- To test this PR, you will need to populate a couple of tables with data, e.g. 

image

image

### CODE REVIEW

**Comment by bergomi02** [comment]
Got the following error when running the databaes update:
image
The error is due to the existing data in the database. Except Production, I believe other environments have some data already. It is very tricky to fix.

**Comment by neophyte57** [comment]
> Got the following error when running the databaes update: image The error is due to the existing data in the database. Except Production, I believe other environments have some data already. It is very tricky to fix.

It seems any existing data in `HealthAuthorityVendor` needs to be re-created in some way as it isn't associated to the correct Care Type.  I could add a SQL statement to the `Up` method to truncate the table prior to other schema changes ...

**Comment by bergomi02** [comment]
> > Got the following error when running the databaes update: image The error is due to the existing data in the database. Except Production, I believe other environments have some data already. It is very tricky to fix.
> 
> It seems any existing data in `HealthAuthorityVendor` needs to be re-created in some way as it isn't associated to the correct Care Type. I could add a SQL statement to the `Up` method to truncate the table prior to other schema changes ...

Hm, HealthAuthoritySite and HealthAuthorityTechicalSupportVendor tables have reference to HealthAuthoityVendor table. 
image

We might need to remove all site data, include some HA data (HealthAuthoityVendor & HealthAuthorityTechicalSupportVendor) in order to apply the schema change. Also, how do you deal with the mapping between technical support and vendor? if HealthAuthorityVendor.HealthAuthorityOrganizationId change to  HealthAuthorityVendor.HealthAuthorityCareTypeId, the technical support will map to multiple care-type-vendor records? The site data from Interior Health and Northern Health, they only have one technical support for their sites.

**Comment by bergomi02** [comment]
Closing PR as PR-2276 replaced this one.

**Pull request closed without merging**
