### PR TITLE
PRIME-1559 Allow CareConnect Sites to add remote users

### PR DESCRIPTION
**Pull request by mtpultz**

### CODE REVIEW

**Review by AnaisHebert — APPROVED** [review]
lgtm ✔✔✔

**Review by johnnyl6 — COMMENTED** [review]
**1. When remote user is added and then change back to careconnect, the warning message still pops up.**

image


**2. View/Update Site Information button is disabled after step 1.**

image

**Comment by mtpultz** [comment]
> **1. When remote user is added and then change back to careconnect, the warning message still pops up.**
> 
> image
> 
> **2. View/Update Remote Practitioners button is disabled after step 1.**
> 
> image

Nice catch @johnnyl6.  I've pushed an update

**Review by johnnyl6 — APPROVED** [review]
LGTM🎆

**Pull request merged**
