### PR TITLE
PRIME-2239 Update HpdidLookup for Provisioners

### PR DESCRIPTION
**Pull request by neophyte57**
To help with testing, take a look at 

image

for use with Postman

### CODE REVIEW

**Comment by bergomi02** [comment]
Tested locally, API works great. It returns a hit only if the enrolment is completed.

One minor thing, I see the word "Licences" and "LicenseNumber". I know we use both spelling in PRIME, like we display label "Licence Number" in UI but "License" is used in table name as LicenseDetail. We might want to keep wording consistent within API. Just a thought. 
image

**Comment by neophyte57** [comment]
> Tested locally, API works great. It returns a hit only if the enrolment is completed.
> 
> One minor thing, I see the word "Licences" and "LicenseNumber". I know we use both spelling in PRIME, like we display label "Licence Number" in UI but "License" is used in table name as LicenseDetail. We might want to keep wording consistent within API. Just a thought. image

I had the dilemma but "licences" is used more often than "licenses": 

image

**Review by Paahn — APPROVED** [review]
LGTM

**Comment by bergomi02** [comment]
Looks good now!
image

**Review by bergomi02 — APPROVED** [review]

**Pull request merged**
