### PR TITLE
Fix Broken OPTIONS Request

### PR DESCRIPTION
**Pull request by james-hollinger**
W H O O P S

### CODE REVIEW

**Comment by neophyte57** [comment]
How does the problem manifest itself?

**Review by hogmann — APPROVED** [review]
LGTM

**Review by mtpultz — APPROVED** [review]

**Review by AnaisHebert — APPROVED** [review]
M E R G E   IT   I N

**Comment by james-hollinger** [comment]
> 
> 
> How does the problem manifest itself?

In local development, the browser makes a pre-flight OPTIONS request before any regular request. ASP tries to enumerate the actions available on the controller by inspecting the return values of the methods. The custom Ok(), BadRequest(), and NotFound() methods I added are seen as actions, but with no routes assigned to them. This causes the API to throw an error saying they are ambiguous since they all have the same route and it can't tell them apart. The fix is to add the attributes I missed tagging the methods as not being actions (they are ActionResults).

**Pull request merged**
