### PR TITLE
PRIME-2001 inappropriate appearance of Update Business License button

### PR DESCRIPTION
**Pull request by mtpultz**
Create a community site and submit, update the expiry date in the database to push the site into renewal, and the business licence button will be displayed, but after submission when InReview it will not be displayed.

### CODE REVIEW

**Comment by AMiKaH** [comment]
Tested, **Renew Site** button won't show after submission, but will be displayed after changing the expiry date to, for example, today. 

However, when updating the business license to renew, the document is not sent to backend and therefore I get **Site registration could not be submitted** error

**Review by AMiKaH — COMMENTED** [review]
Tested, Renew Site button won't show after submission, but will be displayed after changing the expiry date to, for example, today.

However, when updating the business license to renew, the document is not sent to backend and therefore I get **Site registration could not be submitted** error

**Comment by AMiKaH** [comment]
Also, the route to `REMOTE_USER` vs `REMOTE_USERS` is causing an issue in this ticket. I saw that it is fixed in another PR

**Comment by mtpultz** [comment]
> Tested, Renew Site button won't show after submission, but will be displayed after changing the expiry date to, for example, today.
> 
> However, when updating the business license to renew, the document is not sent to backend and therefore I get **Site registration could not be submitted** error

Your mentioning other issues that are covered by other tasks in the sprint.  All this PR does is affect the button.  Does it do that or not?

**Review by AMiKaH — APPROVED** [review]

**Comment by AMiKaH** [comment]
It does what it's supposed to do. I just mentioned the issue as I came across it. Too many small PRs, may be better to be in one PR that encompasses all the issues so that we can test one and not multiple PRs? Just a thought

**Pull request merged**
