### PR TITLE
1234! Wooo!

### PR DESCRIPTION
**Pull request by james-hollinger**
🍰🍰🍰
🍰🎂🍰
🍰🍰🍰

### CODE REVIEW

**Review by mtpultz — APPROVED** [review]
Honestly, this is some good work!  This is kind of hard work and dedication to detail that really shows the kind of polish we consider important in order for us to meet our definition of done.

**Review by AnaisHebert — CHANGES_REQUESTED** [review]
needs more 5678

**Review by neophyte57 — APPROVED** [review]
XD

**Review by AnaisHebert — APPROVED** [review]
🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️🤸‍♀️

**Review by hogmann — APPROVED** [review]
🔢

**Review by itchison — APPROVED** [review]
Someone should consider how this PR works with the changes in this PR https://github.com/bcgov/moh-prime/pull/1234

**Comment by james-hollinger** [comment]
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
🦜🦜🦜🦜

**Comment by AnaisHebert** [comment]
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜🦜🦜🦜🦜🦜🦜
> 🦜🦜🦜🦜

Such a good point

**Review by johnnyl6 — APPROVED** [review]
✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨

**Comment by ajdeziel** [comment]
🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 🥇 

### GOOOOOOO TEEEAMMMM!!!!

**Pull request merged**
