### PR TITLE
Fix so Enrollment and Site Registration tests should be now working

### PR DESCRIPTION
**Pull request by neophyte57**
See `prime-e2e-tests\README.md`.  

Ran all tests successfully against `dev` (or `develop` code locally) and `pr-1517` (Angular 12) OpenShift environments

### CODE REVIEW

**Review by johnnyl6 — COMMENTED** [review]
confirmed that enrolment & site test are working.👍

it seems that `MedicalOfficeAssistant_HappyPath` test runs well until the `Terms of Access` page. Might need to click the continue button and accept the terms of access to complete the enrolment?

image

**Comment by neophyte57** [comment]
> confirmed that enrolment & site test are working.👍
> 
> it seems that `MedicalOfficeAssistant_HappyPath` test runs well until the `Terms of Access` page. Might need to click the continue button and accept the terms of access to complete the enrolment?
> 
> image

Good point @johnnyl6 ; I extended the test so it goes beyond the "Next Steps" screen

**Review by johnnyl6 — APPROVED** [review]
🎉

**Review by hogmann — APPROVED** [review]
LGTM Seems to run

**Pull request merged**
