### PR TITLE
PRIME-2390 and PRIME-2559 - CPSBC and BCCNM licence class changes

### PR DESCRIPTION
**Pull request by neophyte57**
Note that "Temporarily Inactive" licence class is used in Production and "Assessment" licence class needs to be deprecated properly (with later PR).

PR also adds sorting of licence classes by weight on Admin screen.

### CODE REVIEW

**Comment by bergomi02** [comment]
We can take care of "Temporarily Inactive" with the disable feature added in oral health professional ticket. 
I think there is missing change around "Assessment" license class. It now splits to two: "Assessment - specialty" and "Assessment family". It was not highlighted in the current excel spreadsheet but it was highlighted in the older one when I worked on it.

**Comment by neophyte57** [comment]
Need to refresh database

**Comment by neophyte57** [comment]
> We can take care of "Temporarily Inactive" with the disable feature added in oral health professional ticket. I think there is missing change around "Assessment" license class. It now splits to two: "Assessment - specialty" and "Assessment family". It was not highlighted in the current excel spreadsheet but it was highlighted in the older one when I worked on it.

Left "Assessment" and "Temporarily Inactive" for later PR, as well as wider issue of changing algorithm for assigning TOAs per licence class

**Review by bergomi02 — APPROVED** [review]
LGTM!

**Pull request merged**
