### PR TITLE
PRIME-2301 Update self declaration version effective and any fixes

### PR DESCRIPTION
**Pull request by bergomi02**

### CODE REVIEW

**Comment by neophyte57** [comment]
Paper enrollment SD rows not populated properly?  

image

**Comment by bergomi02** [comment]
> 

let me have a look

**Comment by neophyte57** [comment]
> Paper enrollment SD rows not populated properly?

FYI,

```
select *
from "Enrollee" e 
where upper(e."GPID") like '%BCSC%'
```

run against Production returns 0 results.

**Review by neophyte57 — APPROVED** [review]
LGTM

**Pull request merged**
