### PR TITLE
PRIME-1342 Surface Preferred Name and Preferred Address (Mailing Address) on the Enrolments in Admin

### PR DESCRIPTION
**Pull request by johnnyl6**
- changed label & tooltip text of "mailing address" to "preferred address"
- preferred name is already displayed

### CODE REVIEW

**Review by mtpultz — COMMENTED** [review]
The first part looks good, but the preferred name being surfaced doesn't appear to be in this PR

**Comment by johnnyl6** [comment]
> The first part looks good, but the preferred name being surfaced doesn't appear to be in this PR

It's in the requirement but I believe our current code already implements it. So nothing added for preferred name in this PR.

**Review by AnaisHebert — APPROVED** [review]
lgtm 🎈🎈🎈

**Comment by mtpultz** [comment]
I'm probably missing something, but this seems to indicate that preferred name is not being surfaced for terms of access enrolments in adjudication:

image

**Comment by johnnyl6** [comment]
> @johnnyl6 I'm probably missing something, but this seems to indicate that preferred name is not being surfaced for terms of access enrolments in adjudication. This is TEST based on Jolie's example so you're saying in DEVELOP we're already doing this?
> 
> image

@mtpultz  Is your screen based in develop environment? I did a new enrolment with preferred names filled. I can see it showing in the terms-of-access-enrolment page. 

image

**Review by mtpultz — APPROVED** [review]
image

**Comment by mtpultz** [comment]
@johnnyl6 thanks!!!  Yep, that's exactly what I was asking for confirmation on.  Was definitely in TEST.

**Pull request merged**
