### PR TITLE
PRIME-1987 Fix Paper Enrolment Regulatory Select

### PR DESCRIPTION
**Pull request by mtpultz**
The regulatory selection in Paper Enrolment was not appearing due to no options being in the list

### CODE REVIEW

**Review by AMiKaH — APPROVED** [review]
This will have a conflict with the device provider ticket I believe

**Comment by mtpultz** [comment]
> This will have a conflict with the device provider ticket I believe

Yes, only in that it is in the same file, but not functionally

**Comment by mtpultz** [comment]
> This will have a conflict with the device provider ticket I believe

Only in that it has changes in the same file, but not in functionality which

**Review by james-hollinger — APPROVED** [review]
L 📄 TM

**Pull request merged**
