### PR TITLE
Remote access request button hidden when not editable

### PR DESCRIPTION
**Pull request by mtpultz**

### CODE REVIEW

**Comment by neophyte57** [comment]
I was trying to test this but ended up with this situation.  I think it started by clicking on "PRIME History", getting the toast notification in the screenshot, and then clicking the other left menu items.

image

After F5 refresh, it's behaving OK.

**Comment by neophyte57** [comment]
Another thing unrelated to PR change but I noticed while testing.  I lock the enrollee but the Status History doesn't refresh ... should it?

image

**Review by AnaisHebert — APPROVED** [review]
🎈🎈🎈🎈

**Review by neophyte57 — APPROVED** [review]
I notice that in `develop`, when enrollee is Under Review or approved (but before enrollee accepts ToA), the "Request Remote Access" button is visible but not in `pr-1158` so fix looks good

**Comment by mtpultz** [comment]
@neophyte57 I made a note of those issues you noticed and will PR some fixes.  Nice catch!

**Pull request merged**
