### PR TITLE
PRIME-2388 Mononym missing full name

### PR DESCRIPTION
**Pull request by neophyte57**
To test this PR without having an applicable BCSC test card, make these changes locally:

1. Simulate BCSC with mononym
image

2. Disable back-end checks
image

image

image

### CODE REVIEW

**Comment by bergomi02** [comment]
Tested normal case and also in suggested setting to simulate the specific case. In both cases, the enrollees are able to complete the enrolment. However, there are couple areas showing "null" with last name. 
image

image

**Comment by neophyte57** [comment]
> Tested normal case and also in suggested setting to simulate the specific case. In both cases, the enrollees are able to complete the enrolment. However, there are couple areas showing "null" with last name. image
> 
> image

Should be fixed ... tested with Mononym BCSC test card

**Comment by bergomi02** [comment]
> > Tested normal case and also in suggested setting to simulate the specific case. In both cases, the enrollees are able to complete the enrolment. However, there are couple areas showing "null" with last name. image
> > image
> 
> Should be fixed ... tested with Mononym BCSC test card

Confirmed the display issue is fixed.

**Review by bergomi02 — APPROVED** [review]
Well done! LGTM.

**Pull request merged**
