### PR TITLE
Data changes to implement PRIME-1220

### PR DESCRIPTION
**Pull request by neophyte57**

### CODE REVIEW

**Review by johnnyl6 — APPROVED** [review]
👍

**Review by AnaisHebert — APPROVED** [review]
lgtm✔️

**Comment by james-hollinger** [comment]
LGTM
We still should check that none of these are in use before we merge this into prod

**Review by james-hollinger — APPROVED** [review]
LGTM
We should double check that none of these are in use before we merge this into prod

**Pull request merged**
